version: '3'
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    network_mode: host
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
  web:
    build: .
    ports:
      - "8080:8080"

